image: node:12.12.0
stages:
  - build
  - test
  - build_docker

cache:
  paths:
    - node_modules/

lint:
  stage: test
  script:
    - npm run lint
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  script:
    - npm run test
  artifacts:
    paths:
      - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run build

build_image:
  image: docker:19.03.1
  stage: build_docker
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:19.03.1-dind
  script:
    - docker build -t api-post:1.0.0 .
